- name: Install packages
  become: yes
  package:
    name:
      - rust
      - cargo
      - rustfmt
      - git
      - cmake
      - clippy
      - "@Development Tools"
      - gsl-devel
      - gsl
      - perl-IPC-Cmd # needed for rust openssl-sys
      - clang-devel # needed for buildign some rust packages (e.g. rust-htslib)
