- name: Install packages
  become: yes
  package:
    name:
      - rust
      - cargo
      - rustfmt
      - git
      - cmake
      - clippy
      - "@Development Tools"
      - gsl-devel
      - gsl
