# adapted from https://github.com/gantsign/ansible-role-visual-studio-code
- name: Install Zoom repository
  become: yes
  yum_repository:
    name: zoom
    description: Zoom repository
    file: zoom
    baseurl: https://repo.zoom.us/repo/rpm/release/
    gpgkey: https://zoom.us/linux/download/pubkey?version=5-12-6
    gpgcheck: yes

- name: Install Zoom
  become: yes
  package:
    name:
      - zoom
