# adapted from https://github.com/gantsign/ansible-role-visual-studio-code
- name: Install Zoom repository
  become: true
  yum_repository:
    name: zoom
    description: Zoom repository
    file: zoom
    baseurl: https://repo.zoom.us/repo/rpm/release/
    gpgkey: https://repo.zoom.us/repo/rpm/release/repodata/repomd.xml.key
    gpgcheck: yes

- name: Install Zoom
  become: true
  package:
    name:
      - zoom
